Multi storage account
PhonePe/dedomena pull request #10
Opened 2024-06-19 11:39 UTC by abhigun

2024-06-24 07:34 UTC, koushikr requested changes
Just one comment on something named "stg". Didn't understand why it has to be stg. Rest, lgtm!

2024-07-04 04:02 UTC, abhigun commented on infra/setup.sh
> +export TF_STORAGE_ACCOUNT="tfstatephpstage"$clientname
Missed removing the stage suffix, changed it now

2024-07-09 06:32 UTC, koushikr approved these changes

2024-07-09 06:34 UTC, koushikr approved these changes

2024-07-09 06:35 UTC, koushikr commented
Lgtm. Merging this!

2024-07-09 06:35 UTC, merged